{
 "title": "Application Telemetry (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Python",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "MyCounter",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "python_my_counter_total" }
     ]
    },
    {
     "title": "Scrape_Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scrape_duration_seconds" }
     ]
    },
    {
     "title": "MyGauge",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "python_my_gauge" }
     ]
    },
    {
     "title": "MyHistogram",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "python_my_histogram_bucket{le=\"2.5\"}"
      },
      {
       "expr": "python_my_histogram_bucket{le=\"5.0\"}"
      },
      {
       "expr": "python_my_histogram_bucket{le=\"7.5\"}"
      }
     ]
    }
   ]
  }
 ]
}