version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  elk-demo:
    build:
      context: ./ELKdemo
    container_name: elk-demo
    image: elk-demo
    ports:
      - "8080:8080"
    volumes:
      - ./demo-logs/:/usr/src/log/
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.6.1
    ports:
      - "9600:9600"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
      - elk-demo


    

  