version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  fastapi_postgres_application:
    build:
      context: ./sql_app
    container_name: fastapi_postgres_application
    image: fastapi_postgres_application
    depends_on:
      - db
    ports:
      - "81:80"

  